/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ForevereQ (https://sketchfab.com/ForevereQ)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/barrels-e855c7e941bf42ddaf39c78ab8534ce9
Title: barrel's
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import barrelScene from '../assets/3d/barrels.glb'

// https://discourse.threejs.org/t/how-to-create-ground-and-sky-with-gradient-color-and-extend-indefinitely/48563/3

const Barrels = ({ isRotating, setIsRotating, ...props}) => {

  const barrelsRef = useRef();

  const { nodes, materials } = useGLTF(barrelScene)

  return (
    <a.group ref={barrelsRef} {...props}>
        <mesh         
          geometry={nodes.Cylinder_Material_0.geometry}
          material={materials.Material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh          
          geometry={nodes.Cylinder001_Material_0.geometry}
          material={materials.Material}
          position={[143.309, 24.997, -242.881]}
          rotation={[-1.253, 0, 0]}
          scale={100}
        />
        <mesh         
          geometry={nodes.Cylinder002_Material_0.geometry}
          material={materials.Material}
          position={[259.46, 0, 13.197]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh          
          geometry={nodes.Cylinder003_Material_0.geometry}
          material={materials.Material}
          position={[455.839, -75.364, -169.858]}
          rotation={[0, 0.367, 0]}
          scale={100}
        />
    </a.group>
  )
}

useGLTF.preload('/barrels.glb')

export default Barrels